sudo: true

language: python

python:
- "3.6"

before_install:
- sudo apt-get install libblas-dev
- sudo apt-get install liblapack-dev
- sudo apt-get install gfortran

install:
- pip install pytest pytest-cov coveralls
- pip install wxpython numpy scipy matplotlib
- pip install --no-cache-dir https://github.com/chriskiehl/gooey/tarball/master

before_script:
- python setup.py install
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

script:
- py.test --cov-report term-missing --cov=peakdet

after_success:
- coveralls
