language: python
sudo: false
notifications:
  email: change

python:
  - 3.6

env:
  - LINTING=1
  - TESTING=1
  - DOCTEST=1

before_install:
  - python -m pip install --upgrade pip
  - if [ "${LINTING}" == "1" ]; then
      pip install flake8;
    fi

install:
  - if [ "${DOCTEST}" == "1" ]; then
      pip install -e .[doc,tests];
    else
      pip install -e .[tests];
    fi

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - |
    if [ "${LINTING}" == "1" ]; then
      flake8 peakdet;
    elif [ "${DOCTEST}" == "1" ]; then
      cd docs;
      pip install -r ./requirements.txt;
      make html;
      make doctest;
    else
      py.test --doctest-modules peakdet;
    fi
