language: python
sudo: false

matrix:
    include:
        - python: 3.6
          env:
            - STYLE=1
        - python: 3.6
          env:
            - COVERAGE=1

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update -yq conda

install:
    # we need to use conda to test the wxpython / gooey pipeline...
    - conda create -yq -n peakdet python=$TRAVIS_PYTHON_VERSION
    - source activate peakdet
    - conda install wxpython numpy scipy matplotlib pytest pytest-cov codecov coveralls coverage flake8
    - pip install --no-cache-dir https://github.com/chriskiehl/gooey/tarball/master
    - python setup.py install

before_script:
    # so that matplotlib calls don't utterly fail
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - |
    if [ "${STYLE}" == "1" ]; then
        flake8 peakdet
    else
        if [ "${COVERAGE}" == "1" ]; then
            TEST_ARGS="--cov-report=term-missing --cov=peakdet"
        fi
        py.test ${TEST_ARGS} peakdet;
    fi

after_success:
    - |
    if [ "${COVERAGE}" == "1" ]; then
        codecov; coveralls
    fi
