name: peakdet
channels:
    - conda-forge
dependencies:
    - python=3.6
    - matplotlib
    - numpy
    - pillow
    - pip
    - psutil
    - scipy
    - wxpython
    - pip:
        - git+https://github.com/chriskiehl/Gooey.git#egg=gooey
        - git+https://github.com/rmarkello/peakdet.git#egg=peakdet
